language: python
python:
- '3.7'
dist: xenial
sudo: false
addons:
  ssh_known_hosts: shrimp.octet.services
install: pip install -U tox-travis
script: tox
deploy:
- provider: script
  skip_cleanup: true
  script: bash scripts/deployDocs.sh shrimp.octet.services docs_deploy dev
  on:
    tags: false
    repo: DEX-Company/starfish-api
    all_branches: true
    python: 3.7
